export const OFFICIAL_BBDU_MENU = {
  MONDAY: {
    BREAKFAST: [
      'Ajwain Paratha',
      'Matar Chola',
      'Tea',
      'Milk 200 ml',
      'Banana- 02',
    ],
    LUNCH: [
      'Black Masoor Dal',
      'Lauki Jeera Sabji',
      'Rice',
      'Boondi Raita',
      'Salad',
      'Achaar',
      'Roti',
    ],
    SNACKS: [
      'Vegetable Chowmein',
      'Sauce',
      'Tea',
    ],
    DINNER: [
      'Mix Daal',
      'Aaloo Lobiya ki Sabji',
      'Roti',
      'Rice',
      'Salad',
      'Achaar',
      'Baalu Shahi',
    ],
  },
  TUESDAY: {
    BREAKFAST: [
      'Vegetable Suji Upma',
      'Bread Butter- 04',
      'Milk 200 ml',
      'Tea',
      'Banana- 02',
    ],
    LUNCH: [
      'Arhar Daal',
      'Aaloo Pyaj Sabji',
      'Kheera Raita',
      'Rice',
      'Salad',
      'Achaar',
      'Roti',
    ],
    SNACKS: [
      'Namakpara',
      'Tea',
    ],
    DINNER: [
      'Chola',
      'Aaloo Jeera',
      'Poori / Bhatoora',
      'Jeera Rice',
      'Salad',
      'Achaar',
      'Icecream- 01 (Amul, Creambell, Havmor, Vadilal)',
    ],
  },
  WEDNESDAY: {
    BREAKFAST: [
      'Aaloo Paratha with Hari Chatni',
      'Meethi Daliya',
      'Tea',
      'Banana- 02',
      'Egg- 02',
    ],
    LUNCH: [
      'Paneer Butter Masala',
      'Dal Panchmail',
      'Boondi Raita',
      'Rice',
      'Roti',
      'Salad',
      'Achaar',
    ],
    SNACKS: [
      'Matar Chaat with Onion and chilly',
      'Meethi Chatni or Vegetable Paasta with sauce',
      'Tea',
    ],
    DINNER: [
      'Arhar Daal',
      'Aaloo Soyabean lutputi sabji',
      'Roti',
      'Rice',
      'Salad',
      'Achaar',
      'Meethi Boondi',
    ],
  },
  THURSDAY: {
    BREAKFAST: [
      'Vegetable Poha',
      'Sprouts',
      'Cornflakes',
      'Tea',
      'Milk 200 ml',
      'Banana- 02',
    ],
    LUNCH: [
      'Kadhi Pakoda',
      'Aaloo Jeera with Kasuri Methi',
      'Rice',
      'Salad',
      'Achaar',
      'Roti',
    ],
    SNACKS: [
      'Bhelpuri',
      'Tea',
    ],
    DINNER: [
      'Lauki Chana Daal',
      'Aaloo Parval Sookhi Sabji',
      'Roti',
      'Rice',
      'Salad',
      'Achaar',
      'Rice Kheer',
    ],
  },
  FRIDAY: {
    BREAKFAST: [
      'Poori',
      'Aaloo Matar Tamatar ki Sabji',
      'Tea',
      'Milk 200 ml',
      'Banana- 02',
    ],
    LUNCH: [
      'Rajma Masala',
      'Mix Vegetable',
      'Rice',
      'Kheera Raita',
      'Salad',
      'Achaar',
      'Roti',
    ],
    SNACKS: [
      'Samosa- 02',
      'Meethi Chatni',
      'Tea',
    ],
    DINNER: [
      'Matar Paneer',
      'Veg Biryani',
      'Boondi Raita',
      'Salad',
      'Achaar',
      'Roti',
      'Fruits Custard',
    ],
  },
  SATURDAY: {
    BREAKFAST: [
      'Idli Sambhar',
      'Milk 200 ml',
      'Tea',
      'Cornflakes',
      'Banana- 02',
    ],
    LUNCH: [
      'Arhar Daal',
      'Aaloo Parval',
      'Roti',
      'Rice',
      'Boondi Raita',
      'Salad',
      'Achaar',
    ],
    SNACKS: [
      'Aaloo Matar Sandwich- 02',
      'Sauce',
      'Tea',
    ],
    DINNER: [
      'Black Masoor Dal',
      'Lauki Kofta',
      'Roti',
      'Rice',
      'Salad',
      'Achaar',
      'Suji Halwa',
    ],
  },
  SUNDAY: {
    BREAKFAST: [
      'Chana Daal Kachauri',
      'Hari Chatni',
      'Milk 200 ml',
      'Tea',
      'Banana- 02',
    ],
    LUNCH: [
      'Tehri',
      'Aloo Tamatar Sabji',
      'Hari Chatni',
      'Dahi',
      'Papad',
      'Salad',
      'Achaar',
      'Roti',
    ],
    SNACKS: [
      'Chana Masala',
      'Tea',
    ],
    DINNER: [
      'Arhar Dal Tadka',
      'Kashmiri Dum Aaloo',
      'Egg Curry- 02',
      'Rice',
      'Roti',
      'Salad',
      'Achaar',
      'Jalebi- 02',
    ],
  },
};
